[[subs_vec]]
key_phrases = ["."]
replacement = "."
modifier = "capitalize_next_word"

[[subs_vec]]
key_phrases = [
    "левая скобка",
    "скобка открывается",
    "left parenthesis",
    "open parenthesis",
]
replacement = "("
modifier = "suppress_whitespace_after"

[[subs_vec]]
key_phrases = [
    "правая скобка",
    "скобка закрывается",
    "right parenthesis",
    "close parenthesis",
]
replacement = ")"
modifier = "suppress_whitespace_before"
